[2022-04-11 21:58:30.324] [remoteagent] [info] Extension host agent started.
[2022-04-11 21:58:30.727] [remoteagent] [info] [127.0.0.1][a9b3f004][ManagementConnection] New connection established.
[2022-04-11 21:58:30.737] [remoteagent] [info] [127.0.0.1][3662f0dd][ExtensionHostConnection] New connection established.
[2022-04-11 21:58:31.772] [remoteagent] [info] [127.0.0.1][3662f0dd][ExtensionHostConnection] <1509> Launched Extension Host Process.
[2022-04-11 22:00:26.679] [remoteagent] [info] [127.0.0.1][a9b3f004][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-04-11 22:00:26.692] [remoteagent] [info] [127.0.0.1][3662f0dd][ExtensionHostConnection] <1509> Extension Host Process exited with code: 0, signal: null.
[2022-04-11 22:00:26.692] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-04-11 22:00:30.279] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-04-11 22:00:30.279] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-04-11 22:00:30.372] [remoteagent] [info] [127.0.0.1][01959d57][ManagementConnection] New connection established.
[2022-04-11 22:00:30.424] [remoteagent] [info] [127.0.0.1][1b619736][ExtensionHostConnection] New connection established.
[2022-04-11 22:00:30.429] [remoteagent] [info] [127.0.0.1][1b619736][ExtensionHostConnection] <1698> Launched Extension Host Process.
[2022-04-11 22:00:32.872] [remoteagent] [error] ["Error: Could not find pty on pty host","    at C._throwIfNoPty (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:20:5336)","    at C.updateTitle (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:20:1676)","    at Object.call (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:13:8332)","    at E.onPromise (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:4867)","    at E.onRawMessage (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:4262)","    at /home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:3554","    at L.invoke (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:8:145)","    at l.fire (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:8:1856)","    at process.U (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:6:34661)","    at process.emit (node:events:390:28)","    at emit (node:internal/child_process:917:12)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-04-11 22:05:30.280] [remoteagent] [info] New EH opened, aborting shutdown
[2022-04-11 23:58:52.900] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-04-12 00:24:36.837] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-04-12 00:24:37.033] [remoteagent] [info] [127.0.0.1][01959d57][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-04-12 00:24:37.245] [remoteagent] [info] [127.0.0.1][01959d57][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-04-12 00:24:38.338] [remoteagent] [error] ["Error: Could not find pty on pty host","    at C._throwIfNoPty (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:20:5336)","    at C.updateIcon (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:20:1736)","    at Object.call (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:13:8332)","    at E.onPromise (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:4867)","    at E.onRawMessage (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:4262)","    at /home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:3554","    at L.invoke (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:8:145)","    at l.fire (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:8:1856)","    at process.U (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:6:34661)","    at process.emit (node:events:390:28)","    at emit (node:internal/child_process:917:12)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-04-12 00:24:38.352] [remoteagent] [error] ["Error: Could not find pty on pty host","    at C._throwIfNoPty (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:20:5336)","    at C.updateTitle (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:20:1676)","    at Object.call (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:13:8332)","    at E.onPromise (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:4867)","    at E.onRawMessage (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:4262)","    at /home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:3554","    at L.invoke (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:8:145)","    at l.fire (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:8:1856)","    at process.U (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:6:34661)","    at process.emit (node:events:390:28)","    at emit (node:internal/child_process:917:12)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-04-12 00:24:38.352] [remoteagent] [error] ["Error: Could not find pty on pty host","    at C._throwIfNoPty (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:20:5336)","    at C.updateTitle (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:20:1676)","    at Object.call (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:13:8332)","    at E.onPromise (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:4867)","    at E.onRawMessage (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:4262)","    at /home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:12:3554","    at L.invoke (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:8:145)","    at l.fire (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:8:1856)","    at process.U (/home/ubuntu/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/out/vs/platform/terminal/node/ptyHostMain.js:6:34661)","    at process.emit (node:events:390:28)","    at emit (node:internal/child_process:917:12)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-04-12 00:24:43.550] [remoteagent] [info] [127.0.0.1][1b619736][ExtensionHostConnection] <1698> Extension Host Process exited with code: 0, signal: null.
[2022-04-12 00:24:43.550] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-04-12 00:26:46.725] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-04-12 00:26:46.725] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-04-12 00:26:46.821] [remoteagent] [info] [127.0.0.1][b4968df3][ManagementConnection] New connection established.
[2022-04-12 00:26:46.887] [remoteagent] [info] [127.0.0.1][12d029d3][ExtensionHostConnection] New connection established.
[2022-04-12 00:26:46.897] [remoteagent] [info] [127.0.0.1][12d029d3][ExtensionHostConnection] <24854> Launched Extension Host Process.
[2022-04-12 00:27:08.561] [remoteagent] [info] [127.0.0.1][b4968df3][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-04-12 00:27:08.579] [remoteagent] [info] [127.0.0.1][12d029d3][ExtensionHostConnection] <24854> Extension Host Process exited with code: 0, signal: null.
[2022-04-12 00:27:08.579] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-04-12 00:27:08.579] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-04-12 00:32:08.580] [remoteagent] [info] Last EH closed, shutting down
